const svgIcons = {
    message: require('../svgIcons/message.svg'),
    mailBox: require('../svgIcons/mailBox.svg'),
    mailBoxActive: require('../svgIcons/mailBoxActive.svg'),
    home: require('../svgIcons/home.svg'),
    live: require('../svgIcons/live.svg'),
    follow: require('../svgIcons/follow.svg'),
    profile: require('../svgIcons/profile.svg'),
    coin: require('../svgIcons/coin.svg'),
    help: require('../svgIcons/help.svg'),
    logout: require('../svgIcons/logout.svg'),
    settings: require('../svgIcons/settings.svg'),
    vnmese: require('../svgIcons/vnmese.svg'),
    code: require('../svgIcons/code.svg'),
    facebook: require('../svgIcons/facebook.svg'),
    link: require('../svgIcons/link.svg'),
    sendToFriend: require('../svgIcons/sendToFriend.svg'),
    whatsApp: require('../svgIcons/whatsApp.svg'),
    logo: require('../svgIcons/logo.svg'),
    tag: require('../svgIcons/tag.svg'),
    emoji: require('../svgIcons/emoji.svg'),
    play: require('../svgIcons/play.svg'),
    pause: require('../svgIcons/pause.svg'),
    volume: require('../svgIcons/volume.svg'),
    muted: require('../svgIcons/muted.svg'),
    upload_logo: require('../svgIcons/upload_logo.svg'),
    notice: require('../svgIcons/notice.svg'),
};
export default svgIcons;
